image_tag_analysis.settings:
  type: config_object
  label: 'Image Tag Analysis settings'
  mapping:
    ai_prompt:
      type: text
      label: 'AI Prompt'
    cdn_domain:
      type: string
      label: 'CDN Domain'
